### ISSUE TITLE
Prod vs Staging API returns different order of videos

### ISSUE THREAD

**Issue by harrypritchett** [bignerdranch/nerdtv-vue#16]
https://bnr-nerdtv.herokuapp.com returns videos in `DESC` order based on date.
https://bnr-nerdtv-staging.herokuapp.com" returns videos in `ASC` order based on date.

Figure out why the APIs return different ordering and make that consistent from the backend.

**Comment by CodingItWrong** [comment]
The prod API had not been updated in a while. I've deployed it now with the latest changes. Also, previously the API was returning records in ID order, but when setting up a new environment that isn't necessarily chronological order. I've set up the API to return records in chronological order now.
